"""
Reward function
"""
import re
from openai import OpenAI
from concurrent.futures import ThreadPoolExecutor

# ====================================================================================
def parse_llm_evaluation(llm_output: str) -> dict:
    """
    Parses the LLM's evaluation output using regular expressions.

    Args:
        llm_output: The complete string generated by the language model.

    Returns:
        A dictionary containing the critic, conclusion, and final choice.
        Values will be None if the corresponding part is not found.
    """

    def extract_text(input_pattern):
        matches = re.findall(input_pattern, llm_output, re.DOTALL)
        if not matches:
            return None
        return matches[-1].strip()

    think_pattern = r"<think>(.*?)</think>"
    critic_pattern = r"<critics>(.*?)</critics>"
    fallback_critic_pattern = r"<strengths_A>(.*?)</weaknesses_B>"
    strengths_A_pattern = r"<strengths_A>(.*?)</strengths_A>"
    weaknesses_A_pattern = r"<weaknesses_A>(.*?)</weaknesses_A>"
    strengths_B_pattern = r"<strengths_B>(.*?)</strengths_B>"
    weaknesses_B_pattern = r"<weaknesses_B>(.*?)</weaknesses_B>"
    conclusion_pattern = r"<conclusion>(.*?)</conclusion>"
    choice_pattern = r"<choice>(.*?)</choice>"
    fallback_choice_pattern = r"\[\[\s*(A|B)\s*\]\]"

    critics = extract_text(critic_pattern)

    choice = extract_text(choice_pattern)
    if choice is None:
        fallback_match = re.search(fallback_choice_pattern, llm_output)
        if fallback_match:
            choice = fallback_match.group(1)
    if choice is not None:
        if "A" in choice and "B" not in choice:
            choice = "A"
        elif "B" in choice and "A" not in choice:
            choice = "B"
        else:
            choice = None

    return {
        "think": extract_text(think_pattern),
        "critics": critics,
        "strengths_A": extract_text(strengths_A_pattern),
        "weaknesses_A": extract_text(weaknesses_A_pattern),
        "strengths_B": extract_text(strengths_B_pattern),
        "weaknesses_B": extract_text(weaknesses_B_pattern),
        "conclusion": extract_text(conclusion_pattern),
        "choice": choice,
    }
# ====================================================================================

# ====================================================================================
# Left side is the model name, right side is the model invocation frequency
api_score_model_dict = [
    (
        OpenAI(base_url="TODO", api_key="TODO", timeout=60 * 5),
        "gpt-5-mini-2025-08-07", 4
    ),
    (
        OpenAI(base_url="TODO", api_key="TODO", timeout=60 * 5),
        "gpt-5-mini-2025-08-07", 1
    ),
]


def process_score(score):
    if score < 0.5:
        return 0.0
    else:
        return 1.0


def parse_similarity_scores(str_response: str):
    """
    Parses an XML-formatted string to extract six similarity scores and returns them as a tuple.

    Order of returned values:
    (critique_f1, critique_precision, critique_recall, conclusion_f1, conclusion_precision, conclusion_recall)
    """
    try:
        scores = []
        score_tags = ['critique_f1', 'critique_precision', 'critique_recall']
        for tag in score_tags:
            pattern = f"<{tag}>(\d+\.?\d*)</{tag}>"
            match = re.search(pattern, str_response, re.DOTALL)
            if match:
                scores.append(float(match.group(1)))
            else:
                raise ValueError("None")
                # scores.append(None)
        return tuple(scores)
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
        return (None, None, None)

prompt_f1_based_similarity_score = """I will provide you with a generated evaluation content and a reference evaluation content. Your task is to analyze the similarity between the `<Generated Evaluation Content>` and the `<Reference Evaluation Content>` by calculating F1 scores based on their key arguments.

**Core Principle:** Focus exclusively on "Key Arguments" - decisive reasons that are powerful enough to justify the final choice on their own. Identify these core justifications, not minor points.

## Part 1: First check

First check if the generated critique repeats the same point across multiple times. If yes, directly output without conducting part 2:

```xml
<thinking>
    Put here how the generated critique repeats points.
</thinking>

<scores>
    <critique_f1>0</critique_f1>
    <critique_precision>0</critique_precision>
    <critique_recall>0</critique_recall>
</scores>
```

## Part 2: Steps for F1 Score Calculation

1.  **Count Reference Key Arguments (N_ref):**
    *   Check if the reference identifies a **fatal error** (critical factual error, harmful statement, or fundamental misunderstanding).
        *   **If yes**: Only this fatal error counts. Set **N_ref = 1**.
        *   **If no**: Count all unique Key Arguments (decisive reasons that could justify the choice by themselves). Set **N_ref** to this count.

2.  **Count Generated Key Arguments (N_gen):**
    *   Identify all unique Key Arguments in the generated evaluation.
    *   Set **N_gen** to this count.

3.  **Count True Positives (TP):**
    *   Initialize `TP = 0`.
    *   For each reference key argument, search for a match in generated key arguments.
    *   **Matching Rule:** Both **semantic meaning** and **stance** (which response and positive/negative) must align.
        *   Example: "Response A is more detailed" only matches with similar praise of Response A, not Response B.
        *   For fatal errors: Generated must identify the same error in the same response.
    *   Each generated argument can only match once.
    *   Increment `TP` by 1 for each valid match.

4.  **Calculate Scores:**
    *   **Precision_critique:** `TP / N_gen` (0 if N_gen = 0)
    *   **Recall_critique:** `TP / N_ref` (0 if N_ref = 0)
    *   **CritiqueScore:** `2 * (Precision * Recall) / (Precision + Recall)` (0 if sum = 0)

**Output Format (rounded to 4 decimal places):**

```xml
<thinking>
    Put the thinking process here.
</thinking>

<scores>
    <critique_f1>CritiqueScore</critique_f1>
    <critique_precision>Precision_critique</critique_precision>
    <critique_recall>Recall_critique</critique_recall>
</scores>
```

<Generated Evaluation Content>
{critiques}
</Generated Evaluation Content>

<Reference Evaluation Content>
{reference_critiques}
</Reference Evaluation Content>"""

import hashlib
def stable_hash(s: str) -> int:
    return int(hashlib.md5(s.encode("utf-8")).hexdigest(), 16)

def map_human_critiques_to_model_diff_client(human_critiques: str) -> tuple:
    model_weights = api_score_model_dict
    total_weight = sum(w for _, _, w in model_weights)  # 20
    index = stable_hash(human_critiques) % total_weight
    cumulative = 0
    for client, model_name, weight in model_weights:
        cumulative += weight
        if index < cumulative:
            return client, model_name
    return model_weights[-1][0], model_weights[-1][1]

def reward_function_rm_nlhf(data_source, solution_str, ground_truth, extra_info):
    results = parse_llm_evaluation(solution_str)

    # Format error
    reward_format = 0
    if (results["critics"] is None or results["choice"] is None
            or len(results["critics"].split('\n')) > 4
            or len(results["critics"]) > 1500
    ):
        reward_format = -1.0

    # Determine whether GRM's answer is correct
    if results["choice"] == extra_info["winner"]:
        reward_outcome = 1.0
    else:
        reward_outcome = 0.0

    # Obtain MetaRM input
    # Skip calculation when format error, incorrect result, or unlabeled case occurs
    if extra_info.get("dataset_type", None) != "Helpsteer3_A" or reward_format == -1.0 or reward_outcome == 0.0:
        critique_score = 0
        quant_critique_score = 0
        critique_precision = 0
        critique_recall = 0
    else:
        human_critiques = f"""<critics>
<strengths_A>
{extra_info['processed_critique']['strengths_A']}
</strengths_A>

<weaknesses_A>
{extra_info['processed_critique']['weaknesses_A']}
</weaknesses_A>

<strengths_B>
{extra_info['processed_critique']['strengths_B']}
</strengths_B>

<weaknesses_B>
{extra_info['processed_critique']['weaknesses_B']}
</weaknesses_B>
</critics>"""
        human_critiques = human_critiques.strip()
        critics = f"""<critics>
{results["critics"]}
</critics>"""
        critics = critics.strip()
        input_ques = prompt_f1_based_similarity_score.format(critiques=critics, reference_critiques=human_critiques)

        not_match_num = 0
        while True:
            try:
                api_client, api_model = map_human_critiques_to_model_diff_client(human_critiques)

                if "qwen3" in api_model or api_model in ["deepseek-r1-0528"]:
                    extra_body = {"enable_thinking": True}
                else:
                    extra_body = {}

                if "qwen" in api_model:
                    chat_completion = api_client.chat.completions.create(
                        messages=[{"role": "user", "content": input_ques}], model=api_model,
                        extra_body=extra_body, stream=True
                    )
                    reasoning_content = ""
                    answer_content = ""
                    for chunk in chat_completion:
                        # Haven't received content yet
                        if not chunk.choices:
                            continue
                        delta = chunk.choices[0].delta
                        # Only collect reasoning content
                        if hasattr(delta, "reasoning_content") and delta.reasoning_content is not None:
                            reasoning_content += delta.reasoning_content
                        # Received content, start replying
                        if hasattr(delta, "content") and delta.content:
                            answer_content += delta.content
                    content = "<think>\n\n" + reasoning_content + "</think>\n\n" + answer_content

                else:
                    chat_completion = api_client.chat.completions.create(
                        messages=[{"role": "user", "content": input_ques}], model=api_model,
                        extra_body=extra_body
                    )
                    if len(chat_completion.choices) != 0:
                        content = chat_completion.choices[0].message.content
                    else:
                        print(chat_completion)
                        print(input_ques)
                        raise ValueError("chat_completion error")

                critique_score, critique_precision, critique_recall = parse_similarity_scores(content)
                if critique_score is not None and 0 <= critique_score <= 1:
                    quant_critique_score = process_score(critique_score)
                    break
                else:
                    not_match_num += 1
                    if not_match_num >= 3:
                        raise ValueError("MAX-NOT-MATCH")
                    raise ValueError("Not Match")
            except Exception as e:
                print("custom_reward_error", e)
                str_e = str(e)
                if ("no candidates returned" in str_e
                        or "chat_completion error" in str_e
                        or "may contain inappropriate content" in str_e
                        or "MAX-NOT-MATCH" in str_e
                ):
                    critique_score = 0
                    quant_critique_score = 0
                    critique_precision = 0
                    critique_recall = 0
                    break

    # Aggregate rewards
    if reward_format == -1.0:
        final_reward = reward_format
    else:
        final_reward = reward_outcome + 0.5 * quant_critique_score

    # Must return a dict; currently only this format is supported
    reward_dict = {
        "score": final_reward,
        "weighted_sum_score": final_reward,  # This will serve as the score for training MetaRM later
        "reward_format": reward_format,
        "reward_outcome": reward_outcome,
        "reward_critique_score": critique_score,
        "reward_quant_critique_score": quant_critique_score,
        "critique_precision": critique_precision,
        "critique_recall": critique_recall
    }
    return reward_dict

def reward_function_rm_nlhf_batch(data_sources, solution_strs, ground_truths, extra_infos):
    max_workers = 256
    print(f"Rewarding with max_workers = {max_workers}.")
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = []
        for data_source, solution_str, ground_truth, extra_info in zip(
                data_sources, solution_strs, ground_truths, extra_infos, strict=True
        ):
            future = executor.submit(reward_function_rm_nlhf, data_source, solution_str, ground_truth, extra_info)
            futures.append(future)
        results = [future.result() for future in futures]
    return results
# ====================================================================================


# ====================================================================================
def reward_function_outcome(data_source, solution_str, ground_truth, extra_info):
    results = parse_llm_evaluation(solution_str)

    # Format error
    reward_format = 0
    if (results["critics"] is None or results["choice"] is None
            or len(results["critics"].split('\n')) > 4
            or len(results["critics"]) > 1500
    ):
        reward_format = -1.0

    # Determine whether GRM's answer is correct
    if results["choice"] == extra_info["winner"]:
        reward_outcome = 1.0
    else:
        reward_outcome = 0.0

    # Aggregate rewards
    if reward_format == -1.0:
        final_reward = reward_format
    else:
        final_reward = reward_outcome

    # Must return a dict; currently only this format is supported
    reward_dict = {
        "score": final_reward,
        "reward_format": reward_format,
        "reward_outcome": reward_outcome
    }
    return reward_dict

def reward_function_outcome_batch(data_sources, solution_strs, ground_truths, extra_infos):
    max_workers = 256
    print(f"Rewarding with max_workers = {max_workers}.")
    with ThreadPoolExecutor(max_workers=max_workers) as executor:
        futures = []
        for data_source, solution_str, ground_truth, extra_info in zip(
                data_sources, solution_strs, ground_truths, extra_infos, strict=True
        ):
            future = executor.submit(reward_function_outcome, data_source, solution_str, ground_truth, extra_info)
            futures.append(future)
        results = [future.result() for future in futures]
    return results
# ====================================================================================